theme: jekyll-theme-cayman
title: Project Hedra Blog
description: >- # this means to ignore newlines until "baseurl:"
  Blog for the 3D open world lowpoly RPG called Project Hedra
baseurl: "/"
url: "https://blog.projecthedra.com"
logo: /assets/header.png
google_analytics: UA-55659525-12