theme: jekyll-theme-cayman
title: Project Hedra
description: >- # this means to ignore newlines until "baseurl:"
  Blog for the 3D open world lowpoly RPG called Project Hedra
baseurl: "/"
url: "https://blog.projecthedra.com"
logo: /assets/header.png
google_analytics: UA-55659525-12
home: https://blog.projecthedra.com
steam: https://store.steampowered.com/app/1009960/Project_Hedra/
discord: https://discord.gg/AEC4Uab
reddit: https://reddit.com/r/projecthedra
show_excerpts: false